Update azure-static-web-apps-polite-forest-041105700.yml

diff --git a/.github/workflows/azure-static-web-apps-polite-forest-041105700.yml b/.github/workflows/azure-static-web-apps-polite-forest-041105700.yml
--- a/.github/workflows/azure-static-web-apps-polite-forest-041105700.yml
+++ b/.github/workflows/azure-static-web-apps-polite-forest-041105700.yml
@@ -32,10 +32,8 @@ jobs:
           npm run build -- --configuration production
           echo "Build completed. Listing directory contents:"
           ls -R ./dist
-          ls -R ./Client/dist
-          ls -R ./Client/dist/client
       - name: Verify index.html
-        run: if [ ! -f ./Client/dist/client/index.html ]; then echo "index.html not found"; exit 1; fi
+        run: if [ ! -f ./Client/dist/client/browser/index.html ]; then echo "index.html not found"; exit 1; fi
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
@@ -45,7 +43,7 @@ jobs:
           action: "upload"
           app_location: "./Client" # App source code path
           api_location: "" # Api source code path - optional
-          output_location: "dist/client" # Ensure this matches the output path in angular.json
+          output_location: "dist/client/browser" # Ensure this matches the output path in angular.json
 
   close_pull_request_job:
     if: github.event_name == 'pull_request' && github.event.action == 'closed'
